/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hony.java;

/**
 *
 * @author Hony
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMem = new javax.swing.JButton();
        btnDelMem = new javax.swing.JButton();
        btnViewMem = new javax.swing.JButton();
        btnSearchMem = new javax.swing.JButton();
        btnDelBook = new javax.swing.JButton();
        btnViewBook = new javax.swing.JButton();
        btnSearchBook = new javax.swing.JButton();
        btnEditMem = new javax.swing.JButton();
        btnEditBook = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnIssueBook = new javax.swing.JButton();
        btnReturnBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(400, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddMem.setBackground(new java.awt.Color(204, 204, 204));
        btnAddMem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddMem.setForeground(new java.awt.Color(0, 102, 102));
        btnAddMem.setText("Add Member");
        btnAddMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 40));

        btnDelMem.setBackground(new java.awt.Color(204, 204, 204));
        btnDelMem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelMem.setForeground(new java.awt.Color(0, 102, 102));
        btnDelMem.setText("Delete Member");
        btnDelMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMemActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        btnViewMem.setBackground(new java.awt.Color(204, 204, 204));
        btnViewMem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewMem.setForeground(new java.awt.Color(0, 102, 102));
        btnViewMem.setText("View Member");
        btnViewMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMemActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 40));

        btnSearchMem.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchMem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchMem.setForeground(new java.awt.Color(0, 102, 102));
        btnSearchMem.setText("Search Member");
        btnSearchMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, 40));

        btnDelBook.setBackground(new java.awt.Color(204, 204, 204));
        btnDelBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelBook.setForeground(new java.awt.Color(0, 102, 102));
        btnDelBook.setText("Delete Book");
        btnDelBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 40));

        btnViewBook.setBackground(new java.awt.Color(204, 204, 204));
        btnViewBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewBook.setForeground(new java.awt.Color(0, 102, 102));
        btnViewBook.setText("View Book");
        btnViewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 40));

        btnSearchBook.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 102, 102));
        btnSearchBook.setText("Search Book");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 40));

        btnEditMem.setBackground(new java.awt.Color(204, 204, 204));
        btnEditMem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditMem.setForeground(new java.awt.Color(0, 102, 102));
        btnEditMem.setText("Edit Member");
        btnEditMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMemActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 40));

        btnEditBook.setBackground(new java.awt.Color(204, 204, 204));
        btnEditBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditBook.setForeground(new java.awt.Color(0, 102, 102));
        btnEditBook.setText("Edit Book");
        btnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 40));

        btnLogout.setBackground(new java.awt.Color(153, 153, 153));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 90, 40));

        btnAddBook.setBackground(new java.awt.Color(204, 204, 204));
        btnAddBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddBook.setForeground(new java.awt.Color(0, 102, 102));
        btnAddBook.setText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 170, 40));

        btnIssueBook.setBackground(new java.awt.Color(204, 204, 204));
        btnIssueBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIssueBook.setForeground(new java.awt.Color(0, 102, 102));
        btnIssueBook.setText("Issue book");
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 150, 40));

        btnReturnBook.setBackground(new java.awt.Color(204, 204, 204));
        btnReturnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReturnBook.setForeground(new java.awt.Color(0, 102, 102));
        btnReturnBook.setText("Return book");
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 150, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Books ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Members ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, -1));

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hony/java/backgroundImg.jpg"))); // NOI18N
        getContentPane().add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       Login login = new Login();
       setVisible(false);
       login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemActionPerformed
       AddMembers addMember = new AddMembers();
       setVisible(false);
       addMember.setVisible(true);
    }//GEN-LAST:event_btnAddMemActionPerformed

    private void btnDelMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMemActionPerformed
        
       DeleteMember deleteMember = new DeleteMember();
       setVisible(false);
       deleteMember.setVisible(true);
    }//GEN-LAST:event_btnDelMemActionPerformed

    private void btnViewMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMemActionPerformed
        IdToView idToView = new IdToView();
       setVisible(false);
       idToView.setVisible(true);
    }//GEN-LAST:event_btnViewMemActionPerformed

    private void btnSearchMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemActionPerformed
       SearchMembers searchMember = new SearchMembers();
       setVisible(false);
       searchMember.setVisible(true);
    }//GEN-LAST:event_btnSearchMemActionPerformed

    private void btnEditMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMemActionPerformed
        IdToEdit idToEdit = new IdToEdit();
       setVisible(false);
       idToEdit.setVisible(true);
    }//GEN-LAST:event_btnEditMemActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        AddBook addBook = new AddBook();
       setVisible(false);
       addBook.setVisible(true);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDelBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelBookActionPerformed
        DeleteBook deleteBook = new DeleteBook();
       setVisible(false);
       deleteBook.setVisible(true);
    }//GEN-LAST:event_btnDelBookActionPerformed

    private void btnViewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookActionPerformed
        IdToViewBook idToViewBook = new IdToViewBook();
       setVisible(false);
       idToViewBook.setVisible(true);
    }//GEN-LAST:event_btnViewBookActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        SearchBook searchBook = new SearchBook();
       setVisible(false);
       searchBook.setVisible(true);
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void btnEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookActionPerformed
       IdToEditBook idToEditBook = new IdToEditBook();
       setVisible(false);
       idToEditBook.setVisible(true);
    }//GEN-LAST:event_btnEditBookActionPerformed

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed
        IssueBook issueBook = new IssueBook();
       setVisible(false);
       issueBook.setVisible(true);
    }//GEN-LAST:event_btnIssueBookActionPerformed

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        ReturnBook returnBook = new ReturnBook();
       setVisible(false);
       returnBook.setVisible(true);
    }//GEN-LAST:event_btnReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddMem;
    private javax.swing.JButton btnDelBook;
    private javax.swing.JButton btnDelMem;
    private javax.swing.JButton btnEditBook;
    private javax.swing.JButton btnEditMem;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchMem;
    private javax.swing.JButton btnViewBook;
    private javax.swing.JButton btnViewMem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
