/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hony.java;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hony
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form Return Book
     */
    
    int finePrice = 100;
   
    
    
    Connection connection;
    public ReturnBook() {
        initComponents();
        connection = Connector.connetorDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMemberId = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtBookId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDelay = new javax.swing.JTextField();
        btnReturn1 = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ReturnBook");
        setMinimumSize(new java.awt.Dimension(400, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MemberID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));
        getContentPane().add(txtMemberId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, 25));

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(0, 153, 153));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 25));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 80, 25));
        getContentPane().add(txtBookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fine");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BookID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtFine.setEnabled(false);
        getContentPane().add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 180, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Delay");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txtDelay.setEnabled(false);
        getContentPane().add(txtDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, 25));

        btnReturn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturn1.setForeground(new java.awt.Color(0, 153, 153));
        btnReturn1.setText("Calculate Dalay");
        btnReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 140, 25));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hony/java/backgroundImg.jpg"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         Home home = new Home();
       setVisible(false);
       home.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    //A function to detele a record from issue_book and insert the record
    // into return_book table using a before delete trigger
    //CREATE DEFINER=`user`@`%` TRIGGER `issue_book_BEFORE_DELETE` BEFORE DELETE ON `issue_book` FOR EACH ROW BEGIN
    //insert into return_book (member_id,book_id,borrow_date,return_date)
    //values(old.member_id,old.book_id,old.borrow_date,old.return_date);
    //END
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
           String sql = "delete from issue_book where member_id=? and book_id=?";
        
        try(PreparedStatement pst = connection.prepareStatement(sql);)
        {
            pst.setString(1, txtMemberId.getText());
            pst.setString(2, txtBookId.getText());
           
           
            if(pst.execute()){
                JOptionPane.showOptionDialog(null, " Some thing went wrong !","Failure",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
            }
                else{
               
                int input = JOptionPane.showOptionDialog(null, "  Returned successfully !","Success",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
                if(input == JOptionPane.OK_OPTION){
                   clear();
                }
            }
            
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn1ActionPerformed
        
              String sqlForDelay = "select * from issue_book where member_id=? and book_id=?";
        
        try(PreparedStatement pst = connection.prepareStatement(sqlForDelay);)
        {
            pst.setString(1, txtMemberId.getText());
            pst.setString(2, txtBookId.getText());
            try(ResultSet rs = pst.executeQuery()){
                if(rs.next()){
                    java.sql.Date returnDate = rs.getDate(4);
                    long days = calculateDelayedDays(returnDate,calculateCurrentDate());
                    txtDelay.setText(Long.toString(days));
                    txtFine.setText(Long.toString(days*finePrice));
                }
                else{
                   JOptionPane.showOptionDialog(null, " Some thing went wrong !","Failure",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null); 
                }
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
       
    }//GEN-LAST:event_btnReturn1ActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtDelay;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtMemberId;
    // End of variables declaration//GEN-END:variables


private void clear() {
        txtBookId.setText("");
        txtMemberId.setText("");
        txtFine.setText("");
        txtDelay.setText("");
        
        
    }

 
    private Date calculateCurrentDate(){
        long millis = System.currentTimeMillis();
        return new java.sql.Date(millis);
    }

    private long calculateDelayedDays(Date returnDate, Date calculateCurrentDate) {
       // To calculate the time difference of two dates 
         long differenceInTime = returnDate.getTime()- calculateCurrentDate.getTime(); 
       // To calculate the no. of days between two dates 
   
        long differenceIndays = differenceInTime/(1000*3600*24);
        if(differenceIndays <=0 )
            return 0;
        else
            return differenceIndays;
        
    }
}
