/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hony.java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hony
 */
public class ViewMember extends javax.swing.JFrame {

    /**
     * Creates new form ViewMember
     */
   
    DefaultTableModel model1;
    DefaultTableModel model2;
    Connection connection;
    
    public ViewMember() {
        initComponents();
                  
    }
    
    public ViewMember(String id) {
        initComponents();
        lblID.setText(id);
        connection = Connector.connetorDB();
        model1 = (DefaultTableModel)tblBookInformaion.getModel();
        model2 = (DefaultTableModel)tblBookNotReturned.getModel();
        showInfo();
        showMemberBookFromDb();
       showMemberBookNotReturnedFromDb();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookInformaion = new javax.swing.JTable();
        lblPhone = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblExpiry = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBookNotReturned = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Member");
        setMinimumSize(new java.awt.Dimension(400, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 80, -1));

        tblBookInformaion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBookInformaion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 110));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BirhDate");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Expiry");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 20));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 20));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 180, 20));

        lblBirth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBirth.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblExpiry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExpiry.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(lblExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, 20));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book already issued : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        tblBookNotReturned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblBookNotReturned);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 400, 110));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Not Returned yet :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hony/java/backgroundImg.jpg"))); // NOI18N
        getContentPane().add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
          Home home = new Home();
          setVisible(false);
          home.setVisible(true);
                            
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewMember().setVisible(true);
        });
    }
    
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblExpiry;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTable tblBookInformaion;
    private javax.swing.JTable tblBookNotReturned;
    // End of variables declaration//GEN-END:variables

      private void showMemberBookFromDb(){
          
        String sqlBookBorrowed = "SELECT name, borrow_date , return_date FROM book\n" +
                             "JOIN issue_book ON  book.id = issue_book.book_id\n" +
                             "WHERE issue_book.member_id =?";
        try( PreparedStatement pst = connection.prepareStatement(sqlBookBorrowed);   ){
            pst.setString(1,lblID.getText());
            try(ResultSet rs = pst.executeQuery()){
                if(rs.next()){
                tblBookInformaion.setModel(DbUtils.resultSetToTableModel(rs));
                }else{
                   JOptionPane.showOptionDialog(null,"No book exist for this Member","Failure",JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null); 
                }         
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
       
       
    }
      
    private void showInfo() {
       String sqlPersonalInfo ="select * from member where id =?";
       
       try(PreparedStatement pst1 = connection.prepareStatement(sqlPersonalInfo);){
           pst1.setString(1,lblID.getText());
           try(ResultSet rs = pst1.executeQuery();){
           if(rs.next()){
                lblName.setText(rs.getString(1)+" "+rs.getString(2));
                lblID.setText(rs.getString(3));
                lblBirth.setText(rs.getDate(4).toString());
                lblPhone.setText(rs.getString(5));
                lblAddress.setText(rs.getString(6));
                lblExpiry.setText(rs.getDate(8).toString());
           }
           else{
               JOptionPane.showOptionDialog(null,"Member does not exist","Failure",JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
               
           }
           
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
               
    }
   

    private void showMemberBookNotReturnedFromDb() {
          String sqlBookBorrowed = "SELECT name, borrow_date , return_date FROM book\n" +
                             "LEFT JOIN return_book ON  book.id = return_book.book_id\n" +
                             "WHERE return_book.member_id =?";
        try( PreparedStatement pst = connection.prepareStatement(sqlBookBorrowed) ;  ){
            pst.setString(1,lblID.getText());
            try(ResultSet rs = pst.executeQuery()){
                if(rs.next()){
                tblBookNotReturned.setModel(DbUtils.resultSetToTableModel(rs));
                }else{
                   JOptionPane.showOptionDialog(null,"No book exist for this Member ","Failure",JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null); 
                }         
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }
}
